### ISSUE TITLE
Keep secrets secret

### ISSUE THREAD

**Issue by nok-ko** [ShakeGuard/ShakeGuard#8]
# The Problem

Some information, like the password to the MongoDB instance and the `express-session` secret string, really really needs to not be public in this repository.

> Yep, still need to figure out how to keep secrets properly. Hng.

_Originally posted by @nok-ko in https://github.com/ShakeGuard/ShakeGuard/pull/7#discussion_r865424548_

## Potential Solutions

I thought about using GitHub's Secrets feature, but I'm not sure if it's worth spending the time to learn that – I can't find a brief overview and it seems geared more for running tests with GitHub Actions than general secret-keeping in dev environments.

## Proposed Solution

I can write a little Node.js script that uses [sftp](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol) to retrieve secret files from the server at `db.nokko.me` – all of you will just need to give me your SSH public keys, and the rest should be smooth sailing.

## To-Do List
Action items for me:
- [x] Set up user accounts for Tracy & Jay on `db.nokko.me`
- [x] Decide where the `.secrets` reference directory will live on the server, put some sort of example file there
    -  Decided on `/home/shakeguard/.secrets/`, there's an `example_secret.json` file inside that directory.
- [x] Write a Node script to retrieve the `.secrets` directory from the server via SFTP
    - [x] Find a good cross-platform SFTP library?
        - [This one](https://www.npmjs.com/package/ssh2-sftp-client) seems well-maintained and easy to use.
- [x] Make sure the Node script knows where to find private keys, on both Mac and Windows. 
    - ~~Maybe just check `git config`?~~
    - Decided to just look in `$HOME/.ssh/id_rsa` by default, and give users the option to use a different path when running the script.
- [ ] Test the script on all of the team members' computers:
    - [x] Katy
    - [ ] Alex
    - [ ] Jay
    - [ ] Tracy
- [x] Set up an account for the `shakeguard` user to do automated testing in the future.
- [x] Add `.secrets/` to the `.gitignore` file!

**Comment by nok-ko** [comment]
So the workflow start-to-finish will look something like:
1. Clone the repo.
2. Run `npm start`.
3. `npm start` detects that there's no `.secrets` directory, calls into the `npm run secrets` script.
4. The `secrets` script tries to find your SSH public key, asks you if it's got the right one.
5. You confirm.
6. The `secrets` script uses the key to authenticate with the server and grab the secrets directory.
7. `npm start` runs the server like normal. On subsequent runs, the grabbing-secrets step is skipped.

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up SSH Public Keys! (20min)](https://trello.com/c/vte3GC45/99-set-up-ssh-public-keys-20min)

**Comment by nok-ko** [comment]
Action items for me:

- [ ] Set up user accounts for Tracy & Jay on `db.nokko.me`
- [ ] Decide where the `.secrets` reference directory will live on the server, put some sort of example file there
- [ ] Write a Node script to retrieve the `.secrets` directory from the server via SFTP
    - [ ] Find a good cross-platform SFTP library?
- [ ] Make sure the Node script knows where to find private keys, on both Mac and Windows. 
    - Maybe just check `git config`?
- [ ] Test the script with all of the team members.
- [ ] Set up an account for the `shakeguard` user to do automated testing in the future.

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make the Node app log into the DB with user+pass authentication – figure out how to store secrets in the GH repo? (1hr)](https://trello.com/c/kEcL9jXy/60-make-the-node-app-log-into-the-db-with-userpass-authentication-figure-out-how-to-store-secrets-in-the-gh-repo-1hr)

**Comment by nok-ko** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finally make the app log into MongoDB with a username and password. (2hr, actual 3hr)](https://trello.com/c/YT2ZHYUG/105-finally-make-the-app-log-into-mongodb-with-a-username-and-password-2hr-actual-3hr)
